openapi: "3.0.1"
info:
  title: "Combined API"
  version: "1.0"
servers:
  - url: "https://localhost:7044/"
    description: "Employee API Server"
  - url: "https://localhost:7207/"
    description: "Contact API Server"
paths:
  "/employee":
    get:
      tags:
        - "Employee"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      tags:
        - "Employee"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
          text/json:
            schema:
              $ref: "#/components/schemas/Employee"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                $ref: "#/components/schemas/Employee"

  "/employee/{id}":
    get:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Employee"
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
            text/json:
              schema:
                $ref: "#/components/schemas/Employee"
    put:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Employee"
          text/json:
            schema:
              $ref: "#/components/schemas/Employee"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Employee"
      responses:
        "200":
          description: "Success"
    delete:
      tags:
        - "Employee"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"

  "/contact":
    get:
      tags:
        - "Contact"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
    post:
      tags:
        - "Contact"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
          text/json:
            schema:
              $ref: "#/components/schemas/Contact"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"

  "/contact/{id}":
    get:
      tags:
        - "Contact"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                $ref: "#/components/schemas/Contact"
    put:
      tags:
        - "Contact"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
          text/json:
            schema:
              $ref: "#/components/schemas/Contact"
          application/*+json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
    delete:
      tags:
        - "Contact"
      parameters:
        - name: "id"
          in: "path"
          required: true
          style: "simple"
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "Success"
          content:
            text/plain:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"
            text/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Contact"

components:
  schemas:
    DateOnly:
      type: "object"
      properties:
        year:
          type: "integer"
          format: "int32"
        month:
          type: "integer"
          format: "int32"
        day:
          type: "integer"
          format: "int32"
        dayOfWeek:
      